import { Listing } from "./types";

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "Seafront Stone Villa with Pool",
    slug: "seafront-stone-villa-batroun",
    location: "Batroun",
    region: "North Lebanon",
    price_per_night: 280,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    images: [],
    bedrooms: 4,
    bathrooms: 3,
    max_guests: 8,
    rating: 4.92,
    review_count: 47,
    amenities: ["Pool", "Sea View", "WiFi", "BBQ", "Parking"],
    is_featured: true,
    host_name: "Georges",
  },
  {
    id: "2",
    title: "Mountain Chalet with Panoramic Views",
    slug: "mountain-chalet-laklouk",
    location: "Laklouk",
    region: "Mount Lebanon",
    price_per_night: 195,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80",
    images: [],
    bedrooms: 3,
    bathrooms: 2,
    max_guests: 6,
    rating: 4.85,
    review_count: 31,
    amenities: ["Fireplace", "Mountain View", "WiFi", "Heating", "Parking"],
    is_featured: true,
    host_name: "Nadia",
  },
  {
    id: "3",
    title: "Cozy Studio Steps from the Beach",
    slug: "cozy-studio-batroun-beach",
    location: "Batroun",
    region: "North Lebanon",
    price_per_night: 85,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    images: [],
    bedrooms: 1,
    bathrooms: 1,
    max_guests: 2,
    rating: 4.78,
    review_count: 63,
    amenities: ["Sea View", "WiFi", "AC", "Kitchen"],
    is_featured: false,
    host_name: "Rami",
  },
  {
    id: "4",
    title: "Heritage House in the Old Souk",
    slug: "heritage-house-batroun-souk",
    location: "Batroun",
    region: "North Lebanon",
    price_per_night: 150,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    images: [],
    bedrooms: 2,
    bathrooms: 2,
    max_guests: 4,
    rating: 4.95,
    review_count: 28,
    amenities: ["Historic", "WiFi", "Courtyard", "AC", "Kitchen"],
    is_featured: true,
    host_name: "Maya",
  },
  {
    id: "5",
    title: "Modern Apartment with Rooftop Terrace",
    slug: "modern-apartment-batroun",
    location: "Batroun",
    region: "North Lebanon",
    price_per_night: 120,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    images: [],
    bedrooms: 2,
    bathrooms: 1,
    max_guests: 4,
    rating: 4.81,
    review_count: 19,
    amenities: ["Rooftop", "WiFi", "AC", "Sea View", "Kitchen"],
    is_featured: false,
    host_name: "Tony",
  },
  {
    id: "6",
    title: "Luxury Villa with Private Garden",
    slug: "luxury-villa-batroun-garden",
    location: "Batroun",
    region: "North Lebanon",
    price_per_night: 350,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    images: [],
    bedrooms: 5,
    bathrooms: 4,
    max_guests: 10,
    rating: 4.97,
    review_count: 12,
    amenities: ["Pool", "Garden", "WiFi", "BBQ", "Parking", "AC"],
    is_featured: true,
    host_name: "Charbel",
  },
  {
    id: "7",
    title: "Rustic Cedar Cabin in the Cedars",
    slug: "rustic-cedar-cabin",
    location: "The Cedars",
    region: "North Lebanon",
    price_per_night: 110,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&q=80",
    images: [],
    bedrooms: 2,
    bathrooms: 1,
    max_guests: 4,
    rating: 4.88,
    review_count: 41,
    amenities: ["Fireplace", "Mountain View", "Hiking", "Heating"],
    is_featured: false,
    host_name: "Fadi",
  },
  {
    id: "8",
    title: "Beachside Penthouse with Sunset Views",
    slug: "beachside-penthouse-batroun",
    location: "Batroun",
    region: "North Lebanon",
    price_per_night: 220,
    currency: "USD",
    cover_image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    images: [],
    bedrooms: 3,
    bathrooms: 2,
    max_guests: 6,
    rating: 4.90,
    review_count: 36,
    amenities: ["Sea View", "Pool", "WiFi", "AC", "Parking", "Balcony"],
    is_featured: false,
    host_name: "Lara",
  },
];
